### ISSUE TITLE
Correct advance for space?

### ISSUE THREAD

**Issue by ZeunO8** [fetisov/ttf2mesh#14]
Using `hhea.advanceWidthMax * fontSize` returns spacing which are too wide. What is the correct way to calculate space advance?

**Comment by fetisov** [comment]
Hello. A space is a normal ttf font character with its own advance value. Therefore, I advise you to use the ttf_glyph_t::advance value of the character ' '.
`int id = ttf_find_glyph(font, ' ');`
`float spacing = font->glyphs[id].advance * font_size;`
