### ISSUE TITLE
What's motivated you to cap the quality to 128?

### ISSUE THREAD

**Issue by Des-Nerger** [fetisov/ttf2mesh#18]
What's motivated you to cap the quality to 128? I wanted to have more triangles and have hacked the `quality` to be a `uint16_t` instead of `uint8_t`, and also increased the limit to 256. After running `ttf2obj` with quality=256 everything seems to be working like expected: more triangles, etc. Are there pitfalls I should know about? For instance, should I also change the call to mesher to have deep=256 instead of 128? 🤔 :
```c
res = mesher(mesh, 256);
```

**Comment by fetisov** [comment]
Hello. The triangulation algorithm has no explicit limit on the number of points. Therefore, it is not necessary to limit yourself to the number 128. This restriction was introduced to protect against incorrect values of the quality parameter. For very large values (much more than 128), the coordinates of the points have little difference and calculation errors with single-precision numbers are possible.
![изображение](https://github.com/fetisov/ttf2mesh/assets/4045906/99d19ead-c5e5-483d-81c9-d71b087396fc)
The figure shows a circle divided into 128 and 256 points. When splitting into 128 points, I considered that the user could not see the difference between a smooth curve and a linear approximation.
