### ISSUE TITLE
Question regarding glyph state after mesh creation

### ISSUE THREAD

**Issue by blaind** [fetisov/ttf2mesh#4]
Not an issue, but rather a question:

after creating a new 2d or 3d mesh with 
```
int ttf_glyph2mesh3d(ttf_glyph_t *glyph, ttf_mesh3d_t **output, uint8_t quality, int features, float depth)
```

do I need to keep the `ttf_glyph_t *glyph` still allocated, or can it be dropped?

Thanks!

**Comment by fetisov** [comment]
Hello. Thank you for question.
2d and 3d meshes are standalone objects which should be freed with ttf_free_mesh/ttf_free_mesh3d functions. After mesh creation using the ttf_glyph_t structure that is part of perent ttf_t object the parent object can be freed with function ttf_free.
The library does not suppose the ttf_glyph_t structure creation or freeing directly by user.
