### ISSUE TITLE
Smooth Shading on the Text Geometry

### ISSUE THREAD

**Issue by Sum80** [fetisov/ttf2mesh#6]
Currently the shading model is Flat.
@fetisov

**Comment by fetisov** [comment]
Hello. Thank you for message. In the current version of the library, normals are calculated in the FLAT shading model using the ttf_glyph2mesh3d function. This function will be improved in the next version of the library. I will inform you in this thread about the results!

**Comment by Sum80** [comment]
@fetisov  Just wanted to check if you had the chance to look in into the shading model ?

**Comment by fetisov** [comment]
Many thanks for the long wait for this important improvement. In the latest version of ttf2mesh added smooth shading.

**Comment by Sum80** [comment]
Thank you very much , indeed it is very impressive and also if you plan future development you can consider adding bevel to the extruded geometry.
